services:
  prometheus:
    image: prom/prometheus:latest
    container_name: Jemlab_SRE_Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - jemlab_sre_monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: Jemlab_SRE_Grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - jemlab_sre_monitoring
    depends_on:
      - prometheus
  
  my_test_appsrv:
    image: my_test_appsrv:v1
    container_name: Jemlab_SRE_AppServer
    networks:
      - jemlab_sre_monitoring
    ports:
      - 7070:80
  
  alertmanger:
    image: prom/alertmanager:latest
    container_name: Jemlab_SRE_Alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - 9093:9093
    networks:
      - jemlab_sre_monitoring
    depends_on:
      - prometheus
  
networks:
  jemlab_sre_monitoring:
    driver: bridge
