global:
   scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'my_test_appsrv'
    static_configs:
      - targets: ['my_test_appsrv:9100']